version: 2

sources:
- name: airbnb
  schema: raw
  tables:
    - name: listings
      identifier: raw_listings
    
    - name: hosts
      identifier: raw_hosts

    - name: reviews
      identifier: raw_reviews
      #config:
      #  loaded_at_field: date
      #  freshness:
      #    warn_after: {count: 1, period: hour}
      #    error_after: {count: 24, period: hour}

    - name: cust_synthetic 
      identifier: RAW_CUST_SYNTHETIC_DATASET # --> bu snowflake'deki orijinal tablo adı
      